### ISSUE TITLE
datepicker - ngModel not defined

### ISSUE THREAD

**Issue by tinybigideas** [angular-ui/bootstrap#1550]
Not sure why this is occurring, although I've been having issues getting the datepicker to work.

HTML:

``` html
<input type="text" class="start-date form-control" datepicker-popup ng-model="dateRange.start" is-open="startDate" ng-click="openDatepicker('start')" ng-readonly="dateRange.type != 'initial'"  />
```

For some reason, in order to get it to show the popup, I have to add datepicker-popup to the input, otherwise nothing happens.

ERROR:

```
Error: [$compile:ctreq] Controller 'ngModel', required by directive 'datepicker', can't be found!
http://errors.angularjs.org/1.2.7/$compile/ctreq?p0=ngModel&p1=datepicker
    at app/vendor/angular/angular.js:78:12
    at getControllers (app/vendor/angular/angular.js:6050:19)
    at nodeLinkFn (app/vendor/angular/angular.js:6221:35)
    at delayedNodeLinkFn (app/vendor/angular/angular.js:6426:11)
    at compositeLinkFn (app/vendor/angular/angular.js:5630:15)
    at publicLinkFn (app/vendor/angular/angular.js:5535:30)
    at boundTranscludeFn (app/vendor/angular/angular.js:5649:21)
    at controllersBoundTransclude [as $transclude] (app/vendor/angular/angular.js:6241:18)
    at ngDirective.link (app/vendor/angular/angular.js:19898:16)
    at nodeLinkFn (app/vendor/angular/angular.js:6220:13) <table datepicker="" show-weeks="showWeeks" class="ng-isolate-scope"> 
```

ng-model is specified my end on the html, and JS $scope. The datepicker works correctly, as in it correctly loads, I can select a date and populate the model. Although, I get these annoying errors each time on load.

What's going on here, anyone have an idea?

**Comment by bcd6** [comment]
@tinybigideas  
I meet the same error. I wonder what your " contradicting directive" cause this? Thany you.

**Comment by AliAdravi** [comment]
I meet the same error, same code is working in another application but not in mine, see the stackoverflow question

http://stackoverflow.com/questions/32235078/ajgularjs-bootstrap-calendar-rendering-partially-with-error-ngmodel-required?noredirect=1#comment52353074_32235078

There is something wrong in some specific condition.
