### ISSUE TITLE
TypeError: undefined is not a function with data-pagination

### ISSUE THREAD

**Issue by michalo2882** [angular-ui/bootstrap#2930]
**Angularjs:** 1.2.26
**Angular-ui:** 0.11.2

I created such view:

```
<table data-pagination="true">
    <thead>
        <tr>
            <th>ID</th>
        </tr>
    </thead>
</table>
```

Got error:
```
TypeError: undefined is not a function
    at Object.fn (http://172.28.176.23:8877/app/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2256:19)
    at Scope.$digest (http://172.28.176.23:8877/app/bower_components/angular/angular.js:12541:29)
    at Scope.$apply (http://172.28.176.23:8877/app/bower_components/angular/angular.js:12806:24)
    at done (http://172.28.176.23:8877/app/bower_components/angular/angular.js:8379:45)
    at completeRequest (http://172.28.176.23:8877/app/bower_components/angular/angular.js:8593:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://172.28.176.23:8877/app/bower_components/angular/angular.js:8532:11) 
```

Removing **data-pagination="true"** fixes issue.
I need this directive for compatibility with Bootstrap Table module (http://wenzhixin.net.cn/p/bootstrap-table/docs/index.html)

**Comment by wesleycho** [comment]
Closing as per comments - see #3396.
