### ISSUE TITLE
Drop-down focus causes $rootScope:inprog Error

### ISSUE THREAD

**Issue by ronaldjeremy** [angular-ui/bootstrap#2954]
I am using the dropdown control in a phonegap application (android).  Part of that is also a checkbox bound a value in the model.  Whenever I would click on the checkbox, then immediately click on the dropdown, a "$rootScope:inprog" error would get thrown such as the following:

```
at Error (native)
at file:///android_asset/www/js/angular1.3.2.min.js:6:416
at l (file:///android_asset/www/js/angular1.3.2.min.js:116:385)
at k.$apply (file:///android_asset/www/js/angular1.3.2.min.js:124:448)
at HTMLInputElement.<anonymous> (file:///android_asset/www/js/angular1.3.2.min.js:219:287)
at HTMLInputElement.m.event.dispatch (file:///android_asset/www/js/jquery-1.11.1.min.js:3:8436)
at HTMLInputElement.r.handle (file:///android_asset/www/js/jquery-1.11.1.min.js:3:5139)
at k.scope.focusToggleElement (file:///android_asset/www/js/ui-bootstrap-tpls-0.11.2.js:1703:29)
at Object.fn (file:///android_asset/www/js/ui-bootstrap-tpls-0.11.2.js:1712:13)
at k.$digest (file:///android_asset/www/js/angular1.3.2.min.js:122:67)
```

I tracked it down to the "self.toggleElement[0].focus();" in scope.focusToggleElement.  What I did was wrap that statement to become:

```
$timeout(function() {
  self.toggleElement[0].focus();
});
```

Im not sure if that is the right way to go about it, but it seemed to prevent the error.  

Of note is that error never happened in desktop Chrome.  It only happened when I was debugging the app and touching those controls on a phnone.

**Comment by rvanbaalen** [comment]
We don't officially support mobile platforms yet with UI Bootstrap.
