### ISSUE TITLE
Hypen parse error in datepicker

### ISSUE THREAD

**Issue by shabetya** [angular-ui/bootstrap#3840]
Hi everyone. I have the next problem. My angular app began not parse "-" in all expression. Exactly in datepicker also I have parse error

Error: [$parse:ueoe] http://errors.angularjs.org/1.2.28/$parse/ueoe?p0=move(
at Error (native)
at http://camper.loc/bower_components/angular/angular.min.js:6:450
at gb.peekToken (http://camper.loc/bower_components/angular/angular.min.js:170:378)
at gb.functionCall (http://camper.loc/bower_components/angular/angular.min.js:177:231)
at gb.primary (http://camper.loc/bower_components/angular/angular.min.js:170:73)
at gb.unary (http://camper.loc/bower_components/angular/angular.min.js:176:73)
at gb.multiplicative (http://camper.loc/bower_components/angular/angular.min.js:175:310)
at gb.additive (http://camper.loc/bower_components/angular/angular.min.js:175:170)
at gb.relational (http://camper.loc/bower_components/angular/angular.min.js:175:34)
at gb.equality (http://camper.loc/bower_components/angular/angular.min.js:174:400)

 type="button" class="btn btn-default btn-sm pull-left" ng-click="move(-1)" tabindex="-1"
it doesn't like "-1" in ng-click move function .

Thanks for any help!

**Comment by T4YoO** [comment]
Same problem.
Version: 0.13.0
angular 1.3.16
```html
<input name="date" type="text" class="form-control"
                   datepicker-popup="dd/MM/yyyy"
                   ng-model="newCompetition.date"
                   datepicker-options="dateOptions"
                   close-text="Fermer"
                   current-text="Aujourd'hui"
                   clear-text="Effacer"
                   is-open="opened"
                   ng-click="open($event)"
                   required />
```
Controller:
```javascript
$scope.open = function ($event) 
{
            $event.preventDefault();
            $event.stopPropagation();
            $scope.opened = true;
};

$scope.dateOptions = 
{
            "show-weeks": "false",
            "starting-day": "1"
};
```

**Comment by amatosc** [comment]
Same problem.
Version: 0.13.0
angular 1.4.1

and also with the pagination:

``Error: [$parse:ueoe] Unexpected end of expression: selectPage(page
http://errors.angularjs.org/1.4.1/$parse/ueoe?p0=selectPage(page
    at REGEX_STRING_REGEXP (http://localhost:4000/companies/bower_components/angular/angular.js:68:12)
    at Object.AST.consume (http://localhost:4000/companies/bower_components/angular/angular.js:12872:13)
    at Object.AST.primary (http://localhost:4000/companies/bower_components/angular/angular.js:12775:14)
    at Object.AST.unary (http://localhost:4000/companies/bower_components/angular/angular.js:12748:19)
    at Object.AST.multiplicative (http://localhost:4000/companies/bower_components/angular/angular.js:12735:21)
    at Object.AST.additive (http://localhost:4000/companies/bower_components/angular/angular.js:12726:21)
    at Object.AST.relational (http://localhost:4000/companies/bower_components/angular/angular.js:12717:21)
    at Object.AST.equality (http://localhost:4000/companies/bower_components/angular/angular.js:12708:21)
    at Object.AST.logicalAND (http://localhost:4000/companies/bower_components/angular/angular.js:12700:21)
    at Object.AST.logicalOR (http://localhost:4000/companies/bower_components/angular/angular.js:12692:21) <a href="" ng-click="selectPage(page - 1, $event)" class="ng-binding">``

**Comment by arsgeografica** [comment]
We had the same issue today, turned out to be the Chrome "Angular Batarang" plugin.  Running in Incognito mode, using the IP of the computer in the network or 127.0.0.1 or disabling Batarang made the app work.

**Comment by arsgeografica** [comment]
Seems to be angular/angularjs-batarang#230...

**Comment by T4YoO** [comment]
Thank you arsgeografica ! Removing batarang from chrome fixed the problem

**Comment by wesleycho** [comment]
Closing, as this appears to not be an issue in UI Bootstrap.
