### ISSUE TITLE
Pagination & error on empty data set

### ISSUE THREAD

**Issue by dovy** [angular-ui/bootstrap#3871]
I have an app where I display the pagination at an empty state. But for some reason, I get this error:
```
Error: [$parse:ueoe] Unexpected end of expression: selectPage(page
http://errors.angularjs.org/1.4.1/$parse/ueoe?p0=selectPage(page
    at REGEX_STRING_REGEXP (http://localhost:9000/bower_components/angular/angular.js:68:12)
    at Object.AST.consume (http://localhost:9000/bower_components/angular/angular.js:12872:13)
    at Object.AST.primary (http://localhost:9000/bower_components/angular/angular.js:12775:14)
    at Object.AST.unary (http://localhost:9000/bower_components/angular/angular.js:12748:19)
    at Object.AST.multiplicative (http://localhost:9000/bower_components/angular/angular.js:12735:21)
    at Object.AST.additive (http://localhost:9000/bower_components/angular/angular.js:12726:21)
    at Object.AST.relational (http://localhost:9000/bower_components/angular/angular.js:12717:21)
    at Object.AST.equality (http://localhost:9000/bower_components/angular/angular.js:12708:21)
    at Object.AST.logicalAND (http://localhost:9000/bower_components/angular/angular.js:12700:21)
    at Object.AST.logicalOR (http://localhost:9000/bower_components/angular/angular.js:12692:21) <a href="" ng-click="selectPage(page + 1, $event)" class="ng-binding">
```

Any ideas why this could be?

**Comment by pkozlowski-opensource** [comment]
> Any ideas why this could be?

Nope. But you can help us to help you be providing clear reproduce scenario, see: 
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by dovy** [comment]
Sorry for the delay. I'll try to reproduce in plunkr tomorrow.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario so we can't act upon this one.
