### ISSUE TITLE
Bug in Pagination : Unexpected end of expression: selectPage(page

### ISSUE THREAD

**Issue by mbejda** [angular-ui/bootstrap#3885]
Stack Trace : 
<pre>
Error: [$parse:ueoe] Unexpected end of expression: selectPage(page
http://errors.angularjs.org/1.3.16/$parse/ueoe?p0=selectPage(page
    at REGEX_STRING_REGEXP (http://localhost:9000/bower_components/angular/angular.js:63:12)
    at Parser.consume (http://localhost:9000/bower_components/angular/angular.js:12151:13)
    at Parser.functionCall (http://localhost:9000/bower_components/angular/angular.js:12426:10)
    at Parser.primary (http://localhost:9000/bower_components/angular/angular.js:12098:24)
    at Parser.unary (http://localhost:9000/bower_components/angular/angular.js:12374:19)
    at Parser.multiplicative (http://localhost:9000/bower_components/angular/angular.js:12357:21)
    at Parser.additive (http://localhost:9000/bower_components/angular/angular.js:12348:21)
    at Parser.relational (http://localhost:9000/bower_components/angular/angular.js:12339:21)
    at Parser.equality (http://localhost:9000/bower_components/angular/angular.js:12330:21)
    at Parser.logicalAND (http://localhost:9000/bower_components/angular/angular.js:12321:21) <a href="" ng-click="selectPage(page + 1, $event)" class="ng-binding">
</pre>

**Angular Version : ** 1.3.16
**Angular Bootstrap Version :**  0.13.0

I managed to track down the bug to this line: 
 https://github.com/angular-ui/bootstrap/blob/master/template/pagination/pagination.html#L3

**Comment by warrendodsworth** [comment]
This was happening to me as well. 

Are you using Chrome Batarang? Because once that's disabled this error message isnt seen. .

**Comment by mbejda** [comment]
@warrendodsworth  I disable Batarang and the error went away. Closing this issue. Good work :+1:

**Comment by warrendodsworth** [comment]
Awesome stuff @mbejda. I also noticed that while Batarang is enabled and the error is visible, the pager still works as usual, same for you? 
I'll probably add this as an issue in Batarang.

**Comment by mbejda** [comment]
@warrendodsworth  yes everything worked as usual when Batarang was enabled. It just logged that strange error.
