### ISSUE TITLE
Tooltip: attribute tooltip-is-open throws error when boolean is passed

### ISSUE THREAD

**Issue by vitto** [angular-ui/bootstrap#4362]
Hi, I'm trying to use the tooltip with this behavior:

On rollover the tooltip open
On click outside the tooltip close

```
<sup
    class="tip-help"
    tooltip="Hello world"
    tooltip-is-open="opened || false"
    data-ng-mouseenter="opened = true"
    click-outside="opened = false"
    tooltip-trigger="none">
    ?
</sup>
```

`click-outside` is a directive which fires on click outside event.

I've also tried with and without `tooltip-trigger="none"` but the problem persists

when I fire `mouseenter` event or `click-outside` I get this error:

```
TypeError: K.assign is not a function
    at r (http://app.soisy.local/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:14241)
    at n (http://app.soisy.local/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:14080)
    at j (http://app.soisy.local/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:13987)
    at Object.fn (http://app.soisy.local/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:16023)
    at m.a.$get.m.$digest (http://app.soisy.local/vendor/angular/angular.min.js:131:356)
    at m.a.$get.m.$apply (http://app.soisy.local/vendor/angular/angular.min.js:134:361)
    at HTMLElement.<anonymous> (http://app.soisy.local/vendor/angular/angular.min.js:250:446)
    at HTMLElement.n.each.n.event.special.(anonymous function).handle (http://app.soisy.local/vendor/jquery/dist/jquery.min.js:3:10169)
    at HTMLElement.n.event.dispatch (http://app.soisy.local/vendor/jquery/dist/jquery.min.js:3:6466)
    at HTMLElement.n.event.add.r.handle (http://app.soisy.local/vendor/jquery/dist/jquery.min.js:3:3241)
```

Am I wrong with some practice or is the `tooltip-is-open` attribute has some problem?

**Comment by Foxandxss** [comment]
Could you please create a plunker for that?

**Comment by outofculture** [comment]
I'm getting `Error: isOpenExp.assign is not a function` followed shortly by `ttScope is null` with 0.13.4. In my case, the `popover-is-open` expression is a function call that returns a boolean. These errors are similarly agnostic to the presence of `popover-trigger="none"`.

(As an aside, the angular-popover-toggle directive is non-functional for me in 0.13.4, but dropping to 0.13.3 allows it to be used as a workaround.)

**Comment by Foxandxss** [comment]
I would need a plunker as well for the related issue @outofculture. If the aside is a different issue, please open an issue with a plunker.

**Comment by RobJacobs** [comment]
See PR #4380

**Comment by vitto** [comment]
I'm using **angular** `1.4.0` and **angular-bootstrap** `0.13.4` which is not available on plunker, I'll try do bake up as soon as I can

**Comment by Foxandxss** [comment]
Just bump the version that plunker has (I tried to update but it is brokish):

```
https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.4/ui-bootstrap.min.js
```

**Comment by vitto** [comment]
Yeah, it was related to expressions

http://embed.plnkr.co/JNqh8l9ZutecBDyRVfB3

**Comment by ima-tech** [comment]
Will there be a new release soon with this bug fix?

**Comment by icfantv** [comment]
@ima-tech we are targeting this week, even tomorrow perhaps.

**Comment by xskif** [comment]
`isOpen` still doesn't work for me.

**Comment by icfantv** [comment]
@xskif, you would be far better served posting your issue on StackOverflow (as documented [here](https://github.com/angular-ui/bootstrap#need-help)) and pasting your code and link to a plunker that people can debug.  Posting a comment on a closed issue is a good way to not receive any assistance.
