### ISSUE TITLE
Object doesn't support property or method 'focus'

### ISSUE THREAD

**Issue by antonama** [angular-ui/bootstrap#5390]
This error happens in IE11 if I try to do **$uibModalInstance.dismiss()** when using only jqLite (without jQuery):

at removeModalWindow (http://localhost:8000/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:3781:11)
at $modalStack.dismiss (http://localhost:8000/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:3962:11)
at modalInstance.dismiss (http://localhost:8000/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:4083:17)

This is caused by the following line of code:

         //move focus to specified element if available, or else to body

        if (elementToReceiveFocus && elementToReceiveFocus.focus) {

          elementToReceiveFocus.focus();

        } else {

          body.focus();

        }

So **body** doesn't support **.focus()** method in IE, because it is a jqLite object, not DOM element.
It seems **eq(0)** before that does nothing in case of jqLite.

**Comment by antonama** [comment]
Original issue https://github.com/angular-ui/bootstrap/issues/5096
