### ISSUE TITLE
http://angular-ui.github.io/bootstrap/ is broken

### ISSUE THREAD

**Issue by carloshpds** [angular-ui/bootstrap#5729]
### Bug description:
```
Failed to instantiate module ui.bootstrap.demo due to:
ReferenceError: FastClick is not defined
    at http://angular-ui.github.io/bootstrap/assets/app.js:3:3
    at Object.invoke (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:41:295)
    at d (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:39:234)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:39:358
    at n (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:7:355)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:39:135)
    at fb (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:43:164)
    at Ac.c (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:20:449)
    at Ac (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:21:259)
    at fe (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:20:69
```

### Link to minimally-working plunker that reproduces the issue:
http://angular-ui.github.io/bootstrap/

**Comment by icfantv** [comment]
@carloshpds, our demo site is working fine.  I would encourage you to disable your browser plugins and try again.  Barring that, try a different browser or computer.

**Comment by carloshpds** [comment]
@icfantv you're right, it works without my extensions. :)
Sorry, my bad.

**Comment by icfantv** [comment]
Awesome, glad to hear it.

**Comment by wesleycho** [comment]
This should now be fixed, even if you are using an adblocker.
