### ISSUE TITLE
angular.js:9503 TypeError: Cannot read property 'split' of undefined     

### ISSUE THREAD

**Issue by vinod-a-ext** [angular-ui/bootstrap#5971]
angular.js:9503 TypeError: Cannot read property 'split' of undefined
    at createParser (http://localhost:4000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:8:9988)
    at parse (http://localhost:4000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:8:10391)
    at d (http://localhost:4000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:8:20405)
    at u.$render (http://localhost:4000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:8:21829)
    at Object.ngModelWatch (http://localhost:4000/$js/angular.js:16927:14)
    at Scope.$digest (http://localhost:4000/$js/angular.js:11890:40)
    at Scope.$apply (http://localhost:4000/$js/angular.js:12151:24)
    at HTMLButtonElement.<anonymous> (http://localhost:4000/$js/angular.js:18085:21)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:4000/$js/jquery.js:4371:9)
    at HTMLButtonElement.elemData.handle (http://localhost:4000/$js/jquery.js:4057:28) undefined

Got an Issue after Upgrading Help Needed?

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
